blueprint:
  name: Notification Test
  description: Testing mobile notification blueprints
  domain: automation
  author: RobinXe
  input:
    notify_time:
      name: Time to notify
      description: Time to notify
      selector:
        time:

    app_selection:
      name: App selection
      description: Apps to notify
      selector:
        device:
          integration: mobile_app
          multiple: false

variables:
  notify_time: !input notify_time
  app_selection: !input app_selection

trigger:
  platform: time
  at: !input 'notify_time'

condition: []

action:
  - alias: Send a notification to each device
    repeat:
      for_each: !input 'app_selection'
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: Test Notification
            message: Hello, multiple device world
mode: single