blueprint:
  name: Saving Session Force Discharge
  description: Automatically discharge battery to grid during saving sessions
  domain: automation
  author: RobinXe
  input:
    saving_session_event_entity:
      name: Saving session events
      description: Your saving session event entity (e.g. event.octopus_energy_{{ACCOUNT_ID}}_octoplus_saving_session_events)
      selector:
        entity:
          filter:
          - domain:
            - event
            integration: octopus_energy
          multiple: false

    inverter_command_mode:
      name: Inverter command mode
      description: The inverter Storage Command Mode entity
      selector:
        entity:
          filter:
            - domain:
              integration: solaredge_modbus_multi
          multiple: false

  source_url: https://github.com/RobinXe/homeassistant/saving_session_discharge.yml
mode: single
