blueprint:
  name: Saving Session Force Discharge
  description: Automatically discharge battery to grid during saving sessions
  domain: automation
  author: RobinXe
  input:
    saving_session_entity:
      name: Saving session
      description: Your saving session entity (e.g. event.octopus_energy_{{ACCOUNT_ID}}_octoplus_saving_sessions)
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
            integration: octopus_energy
          multiple: false

    inverter_device:
      name: Inverter to discharge
      description: The SolarEdge inverter device to force discharge (e.g. Solaredge I1)
      selector:
        device:
          integration: solaredge_modbus_multi
          multiple: false

    inverter_command_mode:
      name: Inverter storage command mode entity
      description: The inverter Storage Command Mode entity, (e.g. Solaredge I1 Storage Command Mode)
      selector:
        entity:
          filter:
            - domain:
              - select
              integration: solaredge_modbus_multi
          multiple: false

    inverter_discharge_limit:
      name: Inverter storage discharge limit entity
      description: The inverter Discharge Limit entity, (e.g. Solaredge I1 Storage Discharge Limit)
      selector:
        entity:
          filter:
            - domain:
              - number
              integration: solaredge_modbus_multi

    discharge_limit:
      name: Discharge limit
      description: Set a maximum discharge rate for the battery (defaults to 6000 W)
      default: 6000
      selector:
        number:
          min: 0
          max: 10000

    test_selector:
      name: Test Selector
      description: Test Selector
      selector:
        entity:
          domain: integration

  source_url: https://github.com/RobinXe/homeassistant/saving_session_discharge.yml
mode: single

variables:
  saving_session_entity: !input saving_session_entity
  inverter_device: !input inverter_device
  inverter_command_mode: !input inverter_command_mode
  inverter_discharge_limit: !input inverter_discharge_limit
  discharge_limit: !input discharge_limit

trigger:
  - platform: state
    entity_id:
      - !input saving_session_entity
    id: "0"
  - platform: state
    entity_id:
      - !input inverter_command_mode
    id: "1"
condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: >-
                  !input saving_session_entity
                state: "on"
              - condition: trigger
                id:
                  - "0"
        sequence:
          - service: number.set_value
            target:
              entity_id: !input inverter_discharge_limit
            data:
              value: !input discharge_limit
          - device_id: !input inverter_device
            domain: select
            entity_id: !input inverter_command_mode
            type: select_option
            option: Discharge to Maximize Export
          - service: persistent_notification.create
            data:
              title: Forced Discharge Started
              message: >
                Forced battery discharging has been started for Saving Session 
                at {{ now().strftime('%H:%M') }} 
                on {{ now().day }}/{{ now().month }}
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: >-
                  !input saving_session_entity
                state: "off"
              - condition: trigger
                id:
                  - "0"
        sequence:
          - device_id: !input inverter_device
            domain: select
            entity_id: !input inverter_command_mode
            type: select_option
            option: Maximize Self Consumption
          - service: persistent_notification.create
            data:
              title: Forced Discharge Stopped
              message: >
                Forced battery discharging has been stopped 
                at {{ now().strftime('%H:%M') }} 
                on {{ now().day }}/{{ now().month }}
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - "1"
              - condition: state
                entity_id: >-
                  !input saving_session_entity
                state: "on"
        sequence:
          - device_id: !input inverter_device
            domain: select
            entity_id: !input inverter_command_mode
            type: select_option
            option: Discharge to Maximize Export
          - service: persistent_notification.create
            data:
              title: Forced Discharge Restarted
              message: >
                Forced battery discharging has been restarted 
                at {{ now().strftime('%H:%M') }} 
                on {{ now().day }}/{{ now().month }}